name: Build

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:

  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        clean: false
        submodules: 'recursive'
    - run: |
        git fetch --prune --unshallow --tags
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Get dependencies and build
      run: |
        go get github.com/rakyll/statik
        export PATH=$PATH:~/go/bin/
        statik -src=models -f
        sudo apt-get update
        sudo apt-get -y install gcc-mingw-w64-x86-64
        sudo apt-get -y install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross
        sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
        chmod +x ./build.sh
        ./build.sh -r b


    - name: Upload binary files (linux_arm)
      uses: actions/upload-artifact@v2
      with:
        name: cloudreve_linux_arm
        path: release/cloudreve*linux_arm.*

